[package]
name = "fast_scraper"
version = "0.1.0"
edition = "2018"

[dependencies]
scraper = "0.12"
reqwest = { version = "0.11", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"